name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Installing the dependencies
      run: |
        sudo apt update
        sudo apt install libssl-dev g++ cmake make -y

    - name: Build the project
      run: |
        chmod +x misc/dist/install-appimage.sh
        misc/dist/install-appimage.sh

    - name: Building the AppImage for vpack
      uses: AppImageCrafters/build-appimage@master
      with:
        recipe: "./misc/scripts/AppImageBuilder_vpack.yml"

    - name: Building the AppImage for vupdate
      uses: AppImageCrafters/build-appimage@master
      with:
        recipe: "./misc/scripts/AppImageBuilder_vupdate.yml"
    
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: |
          ./vpack*.AppImage
          ./vupdate*.AppImage
        tag_name: ${{ github.ref }}
        body: |
          This is an automated release of the ${{ github.ref }} tag.
          The binaries were built on ${{ matrix.os }} using the ${{ matrix.compiler }} compiler.
        draft: true
