name: Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Installing the dependencies
      run: |
        sudo apt update
        sudo apt install libssl-dev g++ cmake make libfuse2 -y

    - name: Build the project
      run: |
        mkdir build && cd build
        cmake .. -DCOMPILE=0 -DCMAKE_BUILD_TYPE=Release
        cmake --build . -j $(nproc) --config Release
        cmake .. -DCOMPILE=1 -DDO_NOT_FORMAT=OFF -DCMAKE_BUILD_TYPE=Release
        cmake --build . -j $(nproc) --config Release --target install
    
    - name: Uploading the artifacts
      uses: actions/upload-artifact@v3
      with:
        name: vlib-linux-gcc-v0.1.2-alpha
        path: ./build/vlib/*

    # - name: Building the AppImage for vpack
    #   uses: AppImageCrafters/build-appimage@master
    #   with:
    #     recipe: "./misc/scripts/AppImageBuilder_vpack.yml"
    #   env:
    #     UPDATE_INFO: gh-releases-zsync|GhostVaibhav|vupdate|latest|*x86_64.AppImage.zsync

    # - name: Building the AppImage for vupdate
    #   uses: AppImageCrafters/build-appimage@master
    #   with:
    #     recipe: "./misc/scripts/AppImageBuilder_vupdate.yml"
    #   env:
    #     UPDATE_INFO: gh-releases-zsync|GhostVaibhav|vupdate|latest|*x86_64.AppImage.zsync
    
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          vlib-linux-gcc-v0.1.2-alpha.zip
        tag_name: v0.1.2-alpha
        draft: true
